import { describe, expect, test } from "bun:test"
import fs from "fs"
import path from "path"
import { PluginManifest } from "@ericsanchezok/synergy-plugin"
import { buildPluginProject } from "../src/commands/build"
import { PluginValidateCommand, validatePluginProject } from "../src/commands/validate"
import { validateThemeAsset } from "../src/lib/theme-assets"
import {
  captureStdout,
  createFixtureProject,
  minimalPluginSource,
  restoreExitCode,
  writeMinimalPlugin,
} from "./fixtures"

const themeSeeds = {
  neutral: "#6B6B6B",
  primary: "#3B82F6",
  success: "#22C55E",
  warning: "#F59E0B",
  error: "#EF4444",
  info: "#3B82F6",
  interactive: "#3B82F6",
  diffAdd: "#22C55E",
  diffDelete: "#EF4444",
}

function themeJson(id: string) {
  return `${JSON.stringify({ name: id, id, light: { seeds: themeSeeds }, dark: { seeds: themeSeeds } }, null, 2)}\n`
}

describe("validatePluginProject", () => {
  test("validates a fresh source project and warns about missing dist", async () => {
    const project = createFixtureProject("validate-source-")
    try {
      writeMinimalPlugin(project, minimalPluginSource("validate-source"))
      const results = await validatePluginProject(project.root)
      expect(results).toContainEqual({
        type: "pass",
        message: "definePlugin() descriptor valid: validate-source@1.0.0",
      })
      expect(results).toContainEqual({
        type: "pass",
        message: "descriptor handler ids match generated contributions",
      })
      expect(results.some((result) => result.message.includes("dist/plugin.json not found"))).toBe(true)
      expect(results.some((result) => result.type === "error")).toBe(false)
    } finally {
      project.cleanup()
    }
  })

  test("rejects a source plugin.json", async () => {
    const project = createFixtureProject("validate-source-json-")
    try {
      writeMinimalPlugin(project, minimalPluginSource("validate-source-json"))
      project.writeFile("plugin.json", "{}")
      const results = await validatePluginProject(project.root)
      expect(results).toContainEqual({
        type: "error",
        message: "Source plugin.json is not allowed; the manifest is generated by build",
      })
    } finally {
      project.cleanup()
    }
  })

  test("reports descriptor failures", async () => {
    const project = createFixtureProject("validate-broken-")
    try {
      writeMinimalPlugin(project, "export default @")
      const results = await validatePluginProject(project.root)
      expect(results.some((result) => result.type === "error")).toBe(true)
    } finally {
      project.cleanup()
    }
  })

  test("checks trusted UI component sources", async () => {
    const missing = createFixtureProject("validate-ui-missing-")
    try {
      writeMinimalPlugin(
        missing,
        `import { definePlugin, workbenchPanel } from "@ericsanchezok/synergy-plugin"
export default definePlugin({
  id: "validate-ui-missing",
  version: "1.0.0",
  description: "Missing UI source fixture",
  contributions: [workbenchPanel({
    id: "panel", label: "Panel", surface: "side", cardinality: "singleton",
    component: { source: "src/panel.tsx" },
  })],
})
`,
      )
      const results = await validatePluginProject(missing.root)
      expect(results).toContainEqual({ type: "error", message: "trusted UI source is missing: src/panel.tsx" })
    } finally {
      missing.cleanup()
    }

    const present = createFixtureProject("validate-ui-present-")
    try {
      writeMinimalPlugin(
        present,
        `import { definePlugin, workbenchPanel } from "@ericsanchezok/synergy-plugin"
export default definePlugin({
  id: "validate-ui-present",
  version: "1.0.0",
  description: "Present UI source fixture",
  contributions: [workbenchPanel({
    id: "panel", label: "Panel", surface: "side", cardinality: "singleton",
    component: { source: "src/panel.tsx" },
  })],
})
`,
      )
      present.writeFile("src/panel.tsx", "export default function Panel() { return null }\n")
      const results = await validatePluginProject(present.root)
      expect(results).toContainEqual({ type: "pass", message: "trusted UI source exists: src/panel.tsx" })
    } finally {
      present.cleanup()
    }
  })

  test("verifies built artifacts and their hashes", async () => {
    const project = createFixtureProject("validate-built-")
    try {
      writeMinimalPlugin(
        project,
        `import { definePlugin, operation } from "@ericsanchezok/synergy-plugin"
export default definePlugin({
  id: "validate-built",
  version: "1.0.0",
  description: "Built fixture",
  contributions: [operation({
    id: "ping", type: "query", input: {}, output: {},
    handler: async () => ({ ok: true }),
  })],
})
`,
      )
      expect(await buildPluginProject(project.root)).toBe(true)
      const results = await validatePluginProject(project.root)
      expect(results).toContainEqual({ type: "pass", message: "generated manifest schema valid" })
      expect(results).toContainEqual({ type: "pass", message: "runtime artifact integrity valid" })
      expect(results.some((result) => result.type === "error")).toBe(false)
    } finally {
      project.cleanup()
    }
  })

  test("detects corrupted artifacts", async () => {
    const project = createFixtureProject("validate-corrupt-")
    try {
      writeMinimalPlugin(
        project,
        `import { definePlugin, operation } from "@ericsanchezok/synergy-plugin"
export default definePlugin({
  id: "validate-corrupt",
  version: "1.0.0",
  description: "Corrupt fixture",
  contributions: [operation({
    id: "ping", type: "query", input: {}, output: {},
    handler: async () => ({ ok: true }),
  })],
})
`,
      )
      expect(await buildPluginProject(project.root)).toBe(true)
      fs.appendFileSync(path.join(project.root, "dist", "runtime", "index.js"), "\n// tampered")
      const results = await validatePluginProject(project.root)
      expect(results).toContainEqual({
        type: "error",
        message: "runtime artifact hash does not match generated manifest",
      })
    } finally {
      project.cleanup()
    }
  })

  test("detects manifest identity mismatches", async () => {
    const project = createFixtureProject("validate-identity-")
    try {
      writeMinimalPlugin(project, minimalPluginSource("validate-identity"))
      expect(await buildPluginProject(project.root)).toBe(true)
      const manifestPath = path.join(project.root, "dist", "plugin.json")
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"))
      manifest.version = "9.9.9"
      fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)
      const results = await validatePluginProject(project.root)
      expect(results).toContainEqual({
        type: "error",
        message: "generated manifest identity does not match definePlugin()",
      })
    } finally {
      project.cleanup()
    }
  })

  test("runtime discovery matches declared executable handlers", async () => {
    const project = createFixtureProject("validate-discovery-")
    try {
      writeMinimalPlugin(
        project,
        `import { definePlugin, operation, tool } from "@ericsanchezok/synergy-plugin"
export default definePlugin({
  id: "validate-discovery",
  version: "1.0.0",
  description: "Discovery fixture",
  contributions: [
    operation({ id: "ping", type: "query", input: {}, output: {}, handler: async () => ({ ok: true }) }),
    tool({ id: "echo", description: "Echo", input: { type: "object" }, handler: async () => "ok" }),
  ],
})
`,
      )
      expect(await buildPluginProject(project.root)).toBe(true)
      const results = await validatePluginProject(project.root, { runtimeDiscovery: true })
      expect(results).toContainEqual({ type: "pass", message: "runtime handlers match generated contributions" })
    } finally {
      project.cleanup()
    }
  })

  test("runtime discovery reports handler mismatches", async () => {
    const project = createFixtureProject("validate-discovery-mismatch-")
    try {
      writeMinimalPlugin(
        project,
        `import { definePlugin, operation } from "@ericsanchezok/synergy-plugin"
export default definePlugin({
  id: "validate-discovery-mismatch",
  version: "1.0.0",
  description: "Discovery mismatch fixture",
  contributions: [operation({
    id: "ping", type: "query", input: {}, output: {},
    handler: async () => ({ ok: true }),
  })],
})
`,
      )
      expect(await buildPluginProject(project.root)).toBe(true)
      const manifestPath = path.join(project.root, "dist", "plugin.json")
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"))
      manifest.contributions.push({
        kind: "tool",
        id: "extra",
        description: "Extra tool",
        input: { type: "object" },
      })
      fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)
      const results = await validatePluginProject(project.root, { runtimeDiscovery: true })
      expect(
        results.some((result) => result.type === "error" && result.message.startsWith("runtime handlers mismatch")),
      ).toBe(true)
    } finally {
      project.cleanup()
    }
  })

  test("PluginValidateCommand prints results and sets the exit code on errors", async () => {
    const project = createFixtureProject("validate-command-")
    try {
      writeMinimalPlugin(project, "export default @")
      const previousExitCode = process.exitCode
      try {
        const { output } = await captureStdout(() =>
          PluginValidateCommand.handler!({ path: project.root, "runtime-discovery": false } as never),
        )
        expect(output).toContain("ERROR")
        expect(process.exitCode).toBe(1)
      } finally {
        restoreExitCode(previousExitCode)
      }

      project.writeFile("src/index.ts", minimalPluginSource("validate-command"))
      const { output } = await captureStdout(() =>
        PluginValidateCommand.handler!({ path: project.root, "runtime-discovery": false } as never),
      )
      expect(output).toContain("PASS")
      expect(output).toContain("WARN")
      expect(process.exitCode ?? 0).toBe(0)
    } finally {
      project.cleanup()
    }
  })
})

describe("validateThemeAsset", () => {
  test("ignores non-theme contributions", () => {
    const project = createFixtureProject("theme-asset-")
    try {
      expect(validateThemeAsset(project.root, { kind: "tool", id: "t" })).toBeUndefined()
    } finally {
      project.cleanup()
    }
  })

  test("requires an asset path", () => {
    const project = createFixtureProject("theme-asset-")
    try {
      expect(() => validateThemeAsset(project.root, { kind: "ui.theme", id: "t" })).toThrow(
        /does not declare an asset path/,
      )
    } finally {
      project.cleanup()
    }
  })

  test("requires an existing asset file", () => {
    const project = createFixtureProject("theme-asset-")
    try {
      expect(() => validateThemeAsset(project.root, { kind: "ui.theme", id: "t", path: "themes/t.json" })).toThrow(
        /asset is missing/,
      )
    } finally {
      project.cleanup()
    }
  })

  test("rejects invalid theme JSON and id mismatches", () => {
    const project = createFixtureProject("theme-asset-")
    try {
      project.writeFile("themes/bad.json", "{not json")
      expect(() => validateThemeAsset(project.root, { kind: "ui.theme", id: "bad", path: "themes/bad.json" })).toThrow(
        /is not valid JSON/,
      )

      project.writeFile("themes/other.json", themeJson("different-id"))
      expect(() =>
        validateThemeAsset(project.root, { kind: "ui.theme", id: "declared-id", path: "themes/other.json" }),
      ).toThrow(/does not match contribution id/)

      const validated = validateThemeAsset(project.root, {
        kind: "ui.theme",
        id: "different-id",
        path: "themes/other.json",
      })
      expect(validated?.theme.id).toBe("different-id")
      expect(validated?.file).toBe(path.join(project.root, "themes", "other.json"))
    } finally {
      project.cleanup()
    }
  })
})
