import z from "zod"
import { Tool } from "./tool"
import { Asset } from "../asset/asset"
import { Voice } from "../voice"
import { Identifier } from "../id/id"
import type { MessageV2 } from "@/session/message-v2"

const MAX_TEXT_CHARS = 5000

const DESCRIPTION = `Synthesize the given text into spoken audio and deliver it as a playable attachment in the conversation.

Use this when the user asks you to speak, narrate, or read something aloud, wants a voice reply or voice message, or requests audio output (e.g. "say this out loud", "汇报这段", "用语音告诉我"). One call produces one audio clip.

The voice output is generated by the configured speech synthesis service (voice.tts in Settings → Voice). When no TTS model is configured the tool is unavailable.

Parameters:
- text: the exact text to speak (required, up to ${MAX_TEXT_CHARS} characters)
- voice: optional provider-specific voice name (e.g. alloy, echo). Defaults to the configured voice.tts.voice.
- instructions: optional natural-language delivery instructions applied on top of the text, e.g. "speak slowly and calmly", "读得热情一点". Defaults to the configured voice.tts.instructions.

Usage notes:
- Keep text conversational; long monologues are better summarized first.
- The audio is delivered as an attachment the user can play; it is not fed back to the model as speech.`

export const speakDisplay = {
  kind: "media-generation",
  toolCard: "hidden",
  media: {
    type: "audio",
    actionLabel: "Generating speech",
    pendingTitle: "Generating speech",
  },
} as const
export const SpeakTool = Tool.define(
  "speak",
  {
    description: DESCRIPTION,
    parameters: z.object({
      text: z.string().max(MAX_TEXT_CHARS).describe("The exact text to synthesize into speech"),
      voice: z
        .string()
        .optional()
        .describe("Provider-specific voice name. Defaults to the configured voice.tts.voice."),
      instructions: z
        .string()
        .optional()
        .describe("Natural-language delivery instructions for the speech, e.g. tone and pacing"),
    }),
    async execute(params, ctx) {
      const text = params.text.trim()
      if (text.length === 0) throw new Error("speak requires non-empty text")

      const result = await Voice.speak({
        text,
        voice: params.voice,
        instructions: params.instructions,
        abortSignal: ctx.abort,
      })

      const extension = result.mimeType === "audio/wav" ? "wav" : "mp3"
      const filename = `speech-${Identifier.ascending("part")}.${extension}`
      const assetId = await Asset.write(Buffer.from(result.data), result.mimeType, filename)
      const bytes = result.data.byteLength

      const attachments: MessageV2.AttachmentPart[] = [
        {
          id: Identifier.ascending("part"),
          sessionID: ctx.sessionID,
          messageID: ctx.messageID,
          type: "attachment",
          mime: result.mimeType,
          filename,
          url: `asset://${assetId}`,
          presentation: { renderer: "audio", size: "medium" },
          model: { mode: "none" },
          metadata: {
            kind: "attachment",
            attachment: {
              originTool: "speak",
              size: bytes,
              deliverable: true,
            },
          },
        },
      ]

      return {
        title: "Speech",
        output: `Speech delivered (${formatSize(bytes)}). The user can play it in the conversation.`,
        metadata: {
          bytes,
          voice: params.voice,
          truncated: false,
          display: speakDisplay,
        },
        attachments,
      }
    },
  },
  {
    display: speakDisplay,
  },
)

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
