export const reviewCopy = {
  workspaceRequired: { id: "review.panel.workspaceRequired", message: "Select a workspace to compare files." },
  sessionRequired: { id: "review.panel.sessionRequired", message: "Open a conversation to review changes." },
  turnUnavailable: { id: "review.panel.turnUnavailable", message: "The selected turn is unavailable." },
  comparisonUnavailable: { id: "review.panel.comparisonUnavailable", message: "The comparison returned no result." },
  authorityUnavailable: {
    id: "review.panel.authorityUnavailable",
    message: "This historical change has no retained workspace authority.",
  },
  contentUnavailable: { id: "review.panel.contentUnavailable", message: "Captured content is unavailable." },
  exporting: { id: "review.panel.exporting", message: "Preparing patch… {done}/{total}" },
  copyFailed: { id: "review.panel.copyFailed", message: "Copy failed. Try exporting the patch instead." },
  sendFailed: { id: "review.panel.sendFailed", message: "The conversation did not accept these comments. Try again." },
  source: { id: "review.panel.source", message: "Comparison" },
  turn: { id: "review.panel.turn", message: "Turn" },
  session: { id: "review.panel.session", message: "Session" },
  worktree: { id: "review.panel.worktree", message: "Working changes" },
  branch: { id: "review.panel.branch", message: "Branch" },
  auto: { id: "review.panel.auto", message: "Auto" },
  unified: { id: "review.panel.unified", message: "Unified" },
  split: { id: "review.panel.split", message: "Split" },
  layout: { id: "review.panel.layout", message: "Diff layout" },
  layoutState: { id: "review.panel.layoutState", message: "Diff layout: {layout}" },
  refresh: { id: "review.panel.refresh", message: "Refresh comparison" },
  loading: { id: "review.panel.loading", message: "Loading comparison…" },
  refreshing: { id: "review.panel.refreshing", message: "Refreshing…" },
  retry: { id: "review.panel.retry", message: "Retry" },
  empty: { id: "review.panel.empty", message: "No changes" },
  filterEmpty: { id: "review.panel.filterEmpty", message: "No files match this filter." },
  filter: { id: "review.panel.filter", message: "Filter files…" },
  files: { id: "review.panel.files", message: "Files" },
  showFiles: { id: "review.panel.showFiles", message: "Show files" },
  hideFiles: { id: "review.panel.hideFiles", message: "Hide files" },
  jump: { id: "review.panel.jump", message: "Jump to file" },
  next: { id: "review.panel.next", message: "Next file" },
  previous: { id: "review.panel.previous", message: "Previous file" },
  expand: { id: "review.panel.expand", message: "Expand all" },
  collapse: { id: "review.panel.collapse", message: "Collapse all" },
  options: { id: "review.panel.options", message: "Review options" },
  fileOptions: { id: "review.panel.fileOptions", message: "File options" },
  wrap: { id: "review.panel.wrap", message: "Wrap lines" },
  wrapEnable: { id: "review.panel.wrapEnable", message: "Enable line wrapping" },
  wrapDisable: { id: "review.panel.wrapDisable", message: "Disable line wrapping" },
  words: { id: "review.panel.words", message: "Word differences" },
  full: { id: "review.panel.full", message: "Show full file" },
  whitespace: { id: "review.panel.whitespace", message: "Show whitespace" },
  ignoreWhitespace: { id: "review.panel.ignoreWhitespace", message: "Ignore whitespace differences" },
  imports: { id: "review.panel.imports", message: "Fold imports" },
  viewed: { id: "review.panel.viewed", message: "Viewed" },
  markViewed: { id: "review.panel.markViewed", message: "Mark as viewed" },
  open: { id: "review.panel.open", message: "Open current file" },
  historical: { id: "review.panel.historical", message: "This version belongs to another workspace binding." },
  copyPath: { id: "review.panel.copyPath", message: "Copy path" },
  versions: { id: "review.panel.versions", message: "File versions" },
  before: { id: "review.panel.before", message: "Before" },
  after: { id: "review.panel.after", message: "After" },
  sourceView: { id: "review.panel.sourceView", message: "Source" },
  preview: { id: "review.panel.preview", message: "Preview" },
  undo: { id: "review.panel.undo", message: "Undo changes" },
  undoFile: { id: "review.panel.undoFile", message: "Undo this file" },
  export: { id: "review.panel.export", message: "Export patch" },
  copyApply: { id: "review.panel.copyApply", message: "Copy git apply command" },
  binary: { id: "review.panel.binary", message: "Binary file" },
  oversized: { id: "review.panel.oversized", message: "This file exceeds the preview size limit." },
  missing: { id: "review.panel.missing", message: "This file does not exist in this version." },
  symlink: { id: "review.panel.symlink", message: "Symbolic links and submodules have no text preview." },
  read: { id: "review.panel.read", message: "Loading file content…" },
  pending: { id: "review.panel.pending", message: "Recording file changes…" },
  partial: { id: "review.panel.partial", message: "Recording is incomplete. Available changes are shown below." },
  comments: { id: "review.panel.comments", message: "Review comments" },
  addComment: { id: "review.panel.addComment", message: "Comment on selected lines" },
  selectLines: { id: "review.panel.selectLines", message: "Select line numbers in the diff to add a comment." },
  comment: { id: "review.panel.comment", message: "Comment" },
  save: { id: "review.panel.save", message: "Save comment" },
  cancel: { id: "review.panel.cancel", message: "Cancel" },
  remove: { id: "review.panel.remove", message: "Delete comment" },
  edit: { id: "review.panel.edit", message: "Edit comment" },
  resolve: { id: "review.panel.resolve", message: "Resolve comment" },
  reopen: { id: "review.panel.reopen", message: "Reopen comment" },
  resolved: { id: "review.panel.resolved", message: "Resolved" },
  obsolete: { id: "review.panel.obsolete", message: "The file changed. This comment keeps its original excerpt." },
  handoff: { id: "review.panel.handoff", message: "Send selected comments" },
  send: { id: "review.panel.send", message: "Send to this conversation" },
  sending: { id: "review.panel.sending", message: "Sending…" },
  sent: { id: "review.panel.sent", message: "Comments accepted by the conversation." },
  notesFailed: { id: "review.panel.notesFailed", message: "Review notes could not be loaded." },
  from: { id: "review.panel.from", message: "Base reference" },
  to: { id: "review.panel.to", message: "Target reference" },
  applyComparison: { id: "review.panel.applyComparison", message: "Compare" },
  readOnly: { id: "review.panel.readOnly", message: "Read only" },
  copied: { id: "review.panel.copied", message: "Copied" },
  patchUnavailable: {
    id: "review.panel.patchUnavailable",
    message: "An applicable patch is unavailable for this file.",
  },
  selectionMixed: { id: "review.panel.selectionMixed", message: "Select a range on one side, up to 200 lines." },
  noTurn: { id: "review.panel.noTurn", message: "Select a turn with recorded file changes." },
  newImports: { id: "review.panel.foldedImports", message: "{count} import lines folded" },
} as const
