export const PLACEHOLDERS = [
  "Fix a TODO in the codebase",
  "What is the tech stack of this project?",
  "Fix broken tests",
  "Explain how authentication works",
  "Find and fix security vulnerabilities",
  "Add unit tests for the user service",
  "Refactor this function to be more readable",
  "What does this error mean?",
  "Help me debug this issue",
  "Generate API documentation",
  "Optimize database queries",
  "Add input validation",
  "Create a new component for...",
  "How do I deploy this project?",
  "Review my code for best practices",
  "Add error handling to this function",
  "Explain this regex pattern",
  "Convert this to TypeScript",
  "Add logging throughout the codebase",
  "What dependencies are outdated?",
  "Help me write a migration script",
  "Implement caching for this endpoint",
  "Add pagination to this list",
  "Create a CLI command for...",
  "How do environment variables work here?",
]

export const PLACEHOLDERS_GLOBAL = [
  "What's on your mind?",
  "Help me write an email",
  "Summarize this article for me",
  "Brainstorm ideas for...",
  "Explain quantum computing simply",
  "Plan a trip to Tokyo",
  "Help me prepare for an interview",
  "Draft a blog post about...",
  "Compare pros and cons of...",
  "Translate this to French",
]
