import type { MessageDescriptor } from "@lingui/core"

export const renderLabels = {
  conflict: {
    id: "tool.render.conflict",
    message: "Visual state changed in another view. Review the restored values before editing.",
  },
  static: { id: "tool.render.static", message: "This visual is read-only." },
  offline: { id: "tool.render.offline", message: "Agent actions are unavailable in an exported visual." },
  busy: { id: "tool.render.busy", message: "Wait for the current visual action to finish." },
  timeout: { id: "tool.render.timeout", message: "The visual did not respond. Retry to restore its saved state." },
  tooLarge: { id: "tool.render.tooLarge", message: "Visual state exceeds 16 KiB." },
  closed: { id: "tool.render.closed", message: "This visual view is no longer active." },
  tooMany: { id: "tool.render.tooMany", message: "Too many visual controls or objects." },
  invalidControls: { id: "tool.render.invalidControls", message: "Invalid visual control definition." },
  invalidVariants: { id: "tool.render.invalidVariants", message: "Invalid visual variant definition." },
  invalidDate: { id: "tool.render.invalidDate", message: "Invalid calendar date." },
  invalidIcon: { id: "tool.render.invalidIcon", message: "Unknown visual icon." },
  feedback: { id: "tool.render.feedback", message: "Feedback on this visual:" },
  parameters: { id: "tool.render.parameters", message: "Parameters" },
  variants: { id: "tool.render.variants", message: "Variants" },
  reset: { id: "tool.render.reset", message: "Reset" },
  original: { id: "tool.render.original", message: "Hold to view original" },
  review: { id: "tool.render.review", message: "Review changes" },
  changes: { id: "tool.render.changes", message: "Apply these visual changes:" },
  previous: { id: "tool.render.previous", message: "Previous month" },
  next: { id: "tool.render.next", message: "Next month" },
  resourceFailed: { id: "tool.render.resourceFailed", message: "A visual resource failed to load." },
  unavailable: { id: "tool.render.unavailable", message: "Visual actions are unavailable in this view." },
  retry: { id: "tool.render.retry", message: "Retry" },
  navigation: { id: "tool.render.navigation", message: "The visual navigated away. Retry to reopen its saved source." },
} as const

export function localizeRenderLabels(_: (message: MessageDescriptor) => string) {
  return {
    conflict: _(renderLabels.conflict),
    static: _(renderLabels.static),
    offline: _(renderLabels.offline),
    busy: _(renderLabels.busy),
    timeout: _(renderLabels.timeout),
    tooLarge: _(renderLabels.tooLarge),
    closed: _(renderLabels.closed),
    tooMany: _(renderLabels.tooMany),
    invalidControls: _(renderLabels.invalidControls),
    invalidVariants: _(renderLabels.invalidVariants),
    invalidDate: _(renderLabels.invalidDate),
    invalidIcon: _(renderLabels.invalidIcon),
    feedback: _(renderLabels.feedback),
    parameters: _(renderLabels.parameters),
    variants: _(renderLabels.variants),
    reset: _(renderLabels.reset),
    original: _(renderLabels.original),
    review: _(renderLabels.review),
    changes: _(renderLabels.changes),
    previous: _(renderLabels.previous),
    next: _(renderLabels.next),
    resourceFailed: _(renderLabels.resourceFailed),
    unavailable: _(renderLabels.unavailable),
    retry: _(renderLabels.retry),
    navigation: _(renderLabels.navigation),
  }
}
