import { describe, expect, test } from "bun:test"
import { extractLinks, findWrapViolations, reflowMarkdown, slugifyAnchor } from "../../script/doc-check"

describe("doc-check link extraction", () => {
  test("extracts relative links with fragments and ignores code fences", () => {
    const markdown = [
      "See [the guide](docs/reference/cli-guide.md#background-service) for details.",
      "",
      "```ts",
      '// const fake = "[not a link](fake.md)"',
      "```",
      "[external](https://example.com/x) is skipped by the checker",
    ].join("\n")
    const links = extractLinks(markdown)
    expect(links).toEqual([
      {
        raw: "docs/reference/cli-guide.md#background-service",
        target: "docs/reference/cli-guide.md",
        fragment: "background-service",
        line: 1,
      },
    ])
  })

  test("ignores fragment-only, scheme, and auto links", () => {
    const markdown = ["[self](#anchor)", "[auto](<https://example.com>)", "[mail](mailto:a@b.c)"].join("\n")
    expect(extractLinks(markdown)).toEqual([])
  })

  test("handles angle-bracket targets", () => {
    const links = extractLinks("[doc](<guide.md#part>)")
    expect(links).toEqual([{ raw: "<guide.md#part>", target: "guide.md", fragment: "part", line: 1 }])
  })
})

describe("doc-check anchor slugs", () => {
  test("slugifies GitHub-style headings", () => {
    expect(slugifyAnchor("Background Service")).toBe("background-service")
    expect(slugifyAnchor("one-home-per-fact")).toBe("one-home-per-fact")
    expect(slugifyAnchor("Archiving (sealed)")).toBe("archiving-sealed")
  })
})

describe("doc-check wrap", () => {
  test("reflows prose but never merges headings, lists, tables, blockquotes, or fences", () => {
    const markdown = [
      "# Title",
      "",
      "This paragraph is split",
      "across two lines.",
      "",
      "- item one",
      "- item two",
      "",
      "| a | b |",
      "| - | - |",
      "",
      "> quoted line",
      "",
      "```ts",
      "const x = 1",
      "const y = 2",
      "```",
      "",
      "End.",
    ].join("\n")
    const { text, joined } = reflowMarkdown(markdown)
    expect(joined).toBe(1)
    expect(text).toContain("This paragraph is split across two lines.")
    expect(text).toContain("- item one\n- item two")
    expect(text).toContain("| a | b |\n| - | - |")
    expect(text).toContain("> quoted line")
    expect(text).toContain("const x = 1\nconst y = 2")
    expect(findWrapViolations(text)).toEqual([])
  })

  test("findWrapViolations reports only prose continuations", () => {
    const markdown = ["Para one", "continues.", "", "## Head", "", "- list", "  continues too"].join("\n")
    expect(findWrapViolations(markdown)).toEqual([1])
  })

  test("reflow is idempotent", () => {
    const markdown = "Line one\nstill one paragraph.\n\nSecond block\nsecond line.\n"
    const first = reflowMarkdown(markdown)
    expect(first.joined).toBe(2)
    const second = reflowMarkdown(first.text)
    expect(second.joined).toBe(0)
    expect(second.text).toBe(first.text)
  })

  test("preserves HTML comment blocks without merging their contents", () => {
    const markdown = [
      "<!-- GENERATED BY gen-cli-reference.ts — DO NOT EDIT BY HAND.",
      "",
      "Regenerate with bun script/gen/gen-cli-reference.ts.",
      "-->",
      "",
      "After the comment.",
    ].join("\n")
    const { text, joined } = reflowMarkdown(markdown)
    expect(joined).toBe(0)
    expect(text).toContain(
      "<!-- GENERATED BY gen-cli-reference.ts — DO NOT EDIT BY HAND.\n\nRegenerate with bun script/gen/gen-cli-reference.ts.\n-->",
    )
  })
})
