export interface ArtifactFile {
  mime: string
  filename?: string
  url?: string
  assetId?: string
  size?: number
  localPath?: string
  metadata?: Record<string, unknown>
  source?: unknown
}

export type AttachmentFile = ArtifactFile

export function joinServerUrl(serverUrl: string, pathname: string): string {
  return `${serverUrl.replace(/\/$/, "")}${pathname.startsWith("/") ? pathname : `/${pathname}`}`
}

export function resolveArtifactUrl(serverUrl: string, file: ArtifactFile): string | undefined {
  if (file.url) {
    if (file.url.startsWith("asset://")) {
      return joinServerUrl(serverUrl, `/asset/${file.url.slice(8)}`)
    }
    if (file.url.startsWith("file://")) {
      return undefined
    }
    if (file.url.startsWith("/")) {
      return joinServerUrl(serverUrl, file.url)
    }
    if (/^(data|https?):/i.test(file.url)) {
      return file.url
    }
    return undefined
  }
  if (file.assetId) {
    return joinServerUrl(serverUrl, `/asset/${file.assetId}`)
  }
  return undefined
}

export function artifactKind(file: ArtifactFile): string {
  if (isPdf(file)) return "PDF"
  if (isHtml(file)) return "HTML"
  if (file.mime === "text/csv") return "CSV"
  if (file.mime.includes("wordprocessingml")) return "DOCX"
  if (file.mime.includes("spreadsheetml")) return "XLSX"
  if (file.mime.includes("presentationml")) return "PPTX"
  if (file.mime === "application/zip") return "ZIP"
  if (file.mime.startsWith("image/")) return file.mime.split("/")[1]?.toUpperCase() ?? "IMAGE"
  return file.mime.split("/")[1]?.toUpperCase() ?? "FILE"
}

export function formatArtifactSize(bytes: number | undefined): string | undefined {
  if (bytes === undefined) return undefined
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function artifactMeta(file: ArtifactFile): string {
  return [artifactKind(file), formatArtifactSize(artifactSize(file)), artifactSource(file)].filter(Boolean).join(" · ")
}

export function artifactColumnCount(files: ArtifactFile[]): number {
  if (files.length <= 1) return files.length
  if (files.length === 2) return 2
  return 3
}

export function artifactColumns(files: ArtifactFile[]): ArtifactFile[][] {
  const count = artifactColumnCount(files)
  if (count === 0) return []

  const columns: ArtifactFile[][] = Array.from({ length: count }, () => [])

  for (let i = 0; i < files.length; i++) {
    columns[i % count].push(files[i])
  }

  return columns.filter((column) => column.length > 0)
}

export function isImageArtifact(file: ArtifactFile): boolean {
  return file.mime.startsWith("image/")
}

export function isPdfArtifact(file: ArtifactFile): boolean {
  return file.mime === "application/pdf"
}

export function isHtmlArtifact(file: ArtifactFile): boolean {
  return file.mime === "text/html"
}

function isPdf(file: ArtifactFile): boolean {
  return isPdfArtifact(file)
}

function isHtml(file: ArtifactFile): boolean {
  return isHtmlArtifact(file)
}

function artifactSize(file: ArtifactFile): number | undefined {
  if (file.size !== undefined) return file.size
  const artifact = file.metadata?.artifact as Record<string, unknown> | undefined
  return typeof artifact?.size === "number" ? artifact.size : undefined
}

function artifactSource(file: ArtifactFile): string | undefined {
  const artifact = file.metadata?.artifact as Record<string, unknown> | undefined
  const originTool = artifact?.originTool
  return typeof originTool === "string" && originTool ? `Generated by ${originTool}` : undefined
}
