export interface AttachmentFile {
  mime: string
  filename?: string
  url?: string
  assetId?: string
  size?: number
  localPath?: string
  metadata?: Record<string, unknown>
  source?: unknown
}

export function joinServerUrl(serverUrl: string, pathname: string): string {
  return `${serverUrl.replace(/\/$/, "")}${pathname.startsWith("/") ? pathname : `/${pathname}`}`
}

export function resolveAttachmentUrl(serverUrl: string, file: AttachmentFile): string | undefined {
  if (file.url) {
    if (file.url.startsWith("asset://")) {
      return joinServerUrl(serverUrl, `/asset/${file.url.slice(8)}`)
    }
    if (file.url.startsWith("file://")) {
      return undefined
    }
    if (file.url.startsWith("/")) {
      return joinServerUrl(serverUrl, file.url)
    }
    if (/^(data|https?):/i.test(file.url)) {
      return file.url
    }
    return undefined
  }
  if (file.assetId) {
    return joinServerUrl(serverUrl, `/asset/${file.assetId}`)
  }
  return undefined
}

export function attachmentKind(file: AttachmentFile): string {
  if (isPdf(file)) return "PDF"
  if (isHtml(file)) return "HTML"
  if (file.mime === "text/csv") return "CSV"
  if (file.mime.includes("wordprocessingml")) return "DOCX"
  if (file.mime.includes("spreadsheetml")) return "XLSX"
  if (file.mime.includes("presentationml")) return "PPTX"
  if (file.mime === "application/zip") return "ZIP"
  if (file.mime.startsWith("image/")) return file.mime.split("/")[1]?.toUpperCase() ?? "IMAGE"
  return file.mime.split("/")[1]?.toUpperCase() ?? "FILE"
}

export function formatAttachmentSize(bytes: number | undefined): string | undefined {
  if (bytes === undefined) return undefined
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function attachmentMeta(file: AttachmentFile): string {
  return [attachmentKind(file), formatAttachmentSize(attachmentSize(file)), attachmentSource(file)]
    .filter(Boolean)
    .join(" · ")
}

export function attachmentColumnCount(files: AttachmentFile[]): number {
  if (files.length <= 1) return files.length
  if (files.length === 2) return 2
  return 3
}

export function attachmentColumns(files: AttachmentFile[]): AttachmentFile[][] {
  const count = attachmentColumnCount(files)
  if (count === 0) return []

  const columns: AttachmentFile[][] = Array.from({ length: count }, () => [])

  for (let i = 0; i < files.length; i++) {
    columns[i % count].push(files[i])
  }

  return columns.filter((column) => column.length > 0)
}

export function isImageAttachment(file: AttachmentFile): boolean {
  return file.mime.startsWith("image/")
}

export function isPdfAttachment(file: AttachmentFile): boolean {
  return file.mime === "application/pdf"
}

export function isHtmlAttachment(file: AttachmentFile): boolean {
  return file.mime === "text/html"
}

function isPdf(file: AttachmentFile): boolean {
  return isPdfAttachment(file)
}

function isHtml(file: AttachmentFile): boolean {
  return isHtmlAttachment(file)
}

function attachmentSize(file: AttachmentFile): number | undefined {
  if (file.size !== undefined) return file.size
  const attachment = file.metadata?.attachment as Record<string, unknown> | undefined
  return typeof attachment?.size === "number" ? attachment.size : undefined
}

function attachmentSource(file: AttachmentFile): string | undefined {
  const attachment = file.metadata?.attachment as Record<string, unknown> | undefined
  const originTool = attachment?.originTool
  return typeof originTool === "string" && originTool ? `Generated by ${originTool}` : undefined
}
