import { splitProps, type ComponentProps } from "solid-js"
import { Dynamic } from "solid-js/web"
import {
  Activity,
  AlignRight,
  Archive,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Ban,
  Binoculars,
  Bot,
  Boxes,
  Brain,
  Bug,
  Building2,
  Cable,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsRight,
  CircleCheck,
  CircleStop,
  CircleX,
  BookDown,
  BookOpen,
  Braces,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudUpload,
  Code,
  Compass,
  Copy,
  CornerDownLeft,
  Cpu,
  Crosshair,
  Diamond,
  Diff,
  Disc,
  Download,
  Ellipsis,
  Eye,
  FilePen,
  FileTerminal,
  FileText,
  Fingerprint,
  FlaskConical,
  Flame,
  Folder,
  FolderPlus,
  Funnel,
  Gauge,
  GitBranch,
  GitMerge,
  Glasses,
  Globe,
  Gpu,
  Grip,
  GripVertical,
  HardDrive,
  HeartPulse,
  Home,
  Image,
  KeyRound,
  Layers,
  LayoutGrid,
  LockKeyhole,
  MailSearch,
  Lightbulb,
  List,
  ListChecks,
  ListFilter,
  ListTodo,
  LogIn,
  Mail,
  Map,
  Maximize,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Microscope,
  Minimize,
  Moon,
  MousePointer2,
  NotebookPen,
  Package,
  PanelBottom,
  PanelBottomClose,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pen,
  Pencil,
  PenLine,
  Pin,
  Plus,
  Quote,
  Radar,
  Regex,
  RefreshCcw,
  Repeat,
  Rocket,
  RotateCw,
  Route,
  Satellite,
  Scale,
  Scan,
  ScanEye,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Share,
  ShieldAlert,
  ShieldCheck,
  Shrink,
  Signal,
  Sigma,
  SlidersHorizontal,
  Sparkles,
  Spline,
  Square,
  SquareCheck,
  SquarePlay,
  Stethoscope,
  Sun,
  Table,
  Tag,
  Telescope,
  Terminal,
  TextSelect,
  Trash2,
  Undo2,
  Redo2,
  Upload,
  User,
  UserPlus,
  UserRoundPen,
  Users,
  X,
  Zap,
  Github,
  Workflow,
} from "lucide-solid"

const icons = {
  activity: Activity,
  "align-right": AlignRight,
  archive: Archive,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  ban: Ban,
  binoculars: Binoculars,
  "book-down": BookDown,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  braces: Braces,
  brain: Brain,
  bug: Bug,
  "building-2": Building2,
  cable: Cable,
  "calendar-days": CalendarDays,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-right": ChevronsRight,
  "circle-check": CircleCheck,
  "circle-stop": CircleStop,
  "circle-x": CircleX,
  "circuit-board": CircuitBoard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "cloud-upload": CloudUpload,
  code: Code,
  compass: Compass,
  copy: Copy,
  "corner-down-left": CornerDownLeft,
  cpu: Cpu,
  crosshair: Crosshair,
  diamond: Diamond,
  diff: Diff,
  disc: Disc,
  download: Download,
  ellipsis: Ellipsis,
  eye: Eye,
  "file-pen": FilePen,
  "file-terminal": FileTerminal,
  "file-text": FileText,
  fingerprint: Fingerprint,
  "flask-conical": FlaskConical,
  flame: Flame,
  folder: Folder,
  "folder-plus": FolderPlus,
  funnel: Funnel,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  github: Github,
  glasses: Glasses,
  globe: Globe,
  gpu: Gpu,
  grip: Grip,
  "grip-vertical": GripVertical,
  "hard-drive": HardDrive,
  "heart-pulse": HeartPulse,
  home: Home,
  image: Image,
  "key-round": KeyRound,
  layers: Layers,
  "layout-grid": LayoutGrid,
  "lock-keyhole": LockKeyhole,
  lightbulb: Lightbulb,
  list: List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "list-todo": ListTodo,
  "log-in": LogIn,
  mail: Mail,
  "mail-search": MailSearch,
  map: Map,
  maximize: Maximize,
  megaphone: Megaphone,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  microscope: Microscope,
  minimize: Minimize,
  moon: Moon,
  "mouse-pointer-2": MousePointer2,
  "notebook-pen": NotebookPen,
  package: Package,
  "panel-bottom": PanelBottom,
  "panel-bottom-close": PanelBottomClose,
  "panel-bottom-open": PanelBottomOpen,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "panel-right": PanelRight,
  "panel-right-close": PanelRightClose,
  "panel-right-open": PanelRightOpen,
  paperclip: Paperclip,
  pen: Pen,
  pencil: Pencil,
  "pen-line": PenLine,
  pin: Pin,
  plus: Plus,
  quote: Quote,
  radar: Radar,
  regex: Regex,
  "refresh-ccw": RefreshCcw,
  repeat: Repeat,
  rocket: Rocket,
  "rotate-cw": RotateCw,
  route: Route,
  satellite: Satellite,
  scale: Scale,
  scan: Scan,
  "scan-eye": ScanEye,
  "scan-search": ScanSearch,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  shrink: Shrink,
  signal: Signal,
  sigma: Sigma,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  spline: Spline,
  square: Square,
  "square-check": SquareCheck,
  "square-play": SquarePlay,
  stethoscope: Stethoscope,
  sun: Sun,
  table: Table,
  tag: Tag,
  telescope: Telescope,
  terminal: Terminal,
  "text-select": TextSelect,
  "trash-2": Trash2,
  "undo-2": Undo2,
  "redo-2": Redo2,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  "user-round-pen": UserRoundPen,
  users: Users,
  x: X,
  zap: Zap,
  workflow: Workflow,
}

export type IconName = keyof typeof icons

export interface IconProps extends Omit<ComponentProps<"svg">, "name"> {
  name: IconName
  size?: "small" | "normal" | "large"
}

export function Icon(props: IconProps) {
  const [local, others] = splitProps(props, ["name", "size", "class", "classList"])
  const Component = () => icons[local.name]

  return (
    <div data-component="icon" data-size={local.size || "normal"}>
      <Dynamic
        component={Component()}
        data-slot="icon-svg"
        class={local.class}
        classList={local.classList}
        size="100%"
        strokeWidth={1.5}
        {...others}
      />
    </div>
  )
}
