import { splitProps, type ComponentProps } from "solid-js"
import { Dynamic } from "solid-js/web"
import {
  AlignRight,
  Archive,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Ban,
  Bot,
  Brain,
  Bug,
  Cable,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsRight,
  CircleCheck,
  CircleX,
  ClipboardList,
  Clock,
  Code,
  Compass,
  Copy,
  CornerDownLeft,
  Diamond,
  Disc,
  Download,
  Ellipsis,
  Eye,
  FileText,
  Folder,
  FolderPlus,
  GitBranch,
  GitMerge,
  Glasses,
  Globe,
  Grip,
  GripVertical,
  Home,
  Image,
  LayoutGrid,
  List,
  ListChecks,
  ListTodo,
  LogIn,
  Mail,
  Maximize,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize,
  Moon,
  MousePointer2,
  NotebookPen,
  PanelBottom,
  PanelBottomClose,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pen,
  PenLine,
  Pin,
  Plus,
  Quote,
  RefreshCcw,
  Repeat,
  Search,
  Server,
  Settings,
  Share,
  ShieldAlert,
  ShieldCheck,
  Shrink,
  Sigma,
  Sparkles,
  Square,
  SquareCheck,
  SquarePlay,
  Sun,
  Table,
  Tag,
  Terminal,
  TextSelect,
  Trash2,
  Undo2,
  Redo2,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  Zap,
  Github,
  Workflow,
} from "lucide-solid"

const icons = {
  "align-right": AlignRight,
  archive: Archive,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  ban: Ban,
  bot: Bot,
  brain: Brain,
  bug: Bug,
  cable: Cable,
  "calendar-days": CalendarDays,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-right": ChevronsRight,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "clipboard-list": ClipboardList,
  clock: Clock,
  code: Code,
  compass: Compass,
  copy: Copy,
  "corner-down-left": CornerDownLeft,
  diamond: Diamond,
  disc: Disc,
  download: Download,
  ellipsis: Ellipsis,
  eye: Eye,
  "file-text": FileText,
  folder: Folder,
  "folder-plus": FolderPlus,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  github: Github,
  glasses: Glasses,
  globe: Globe,
  grip: Grip,
  "grip-vertical": GripVertical,
  home: Home,
  image: Image,
  "layout-grid": LayoutGrid,
  list: List,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "log-in": LogIn,
  mail: Mail,
  maximize: Maximize,
  megaphone: Megaphone,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  minimize: Minimize,
  moon: Moon,
  "mouse-pointer-2": MousePointer2,
  "notebook-pen": NotebookPen,
  "panel-bottom": PanelBottom,
  "panel-bottom-close": PanelBottomClose,
  "panel-bottom-open": PanelBottomOpen,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "panel-right": PanelRight,
  "panel-right-close": PanelRightClose,
  "panel-right-open": PanelRightOpen,
  paperclip: Paperclip,
  pen: Pen,
  "pen-line": PenLine,
  pin: Pin,
  plus: Plus,
  quote: Quote,
  "refresh-ccw": RefreshCcw,
  repeat: Repeat,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  shrink: Shrink,
  sigma: Sigma,
  sparkles: Sparkles,
  square: Square,
  "square-check": SquareCheck,
  "square-play": SquarePlay,
  sun: Sun,
  table: Table,
  tag: Tag,
  terminal: Terminal,
  "text-select": TextSelect,
  "trash-2": Trash2,
  "undo-2": Undo2,
  "redo-2": Redo2,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  x: X,
  zap: Zap,
  workflow: Workflow,
}

export type IconName = keyof typeof icons

export interface IconProps extends Omit<ComponentProps<"svg">, "name"> {
  name: IconName
  size?: "small" | "normal" | "large"
}

export function Icon(props: IconProps) {
  const [local, others] = splitProps(props, ["name", "size", "class", "classList"])
  const Component = () => icons[local.name]

  return (
    <div data-component="icon" data-size={local.size || "normal"}>
      <Dynamic
        component={Component()}
        data-slot="icon-svg"
        class={local.class}
        classList={local.classList}
        size="100%"
        strokeWidth={1.5}
        {...others}
      />
    </div>
  )
}
