const RUNTIME_SHUTDOWN_SETTLE_MARGIN_MS = 5_000
const DESKTOP_SUPERVISOR_SETTLE_MARGIN_MS = 5_000

export const MAX_EXECUTION_CANCEL_GRACE_MS = 60_000

export function resolveRuntimeShutdownTimeoutMs(executionCancelGraceMs: number): number {
  return Math.max(RUNTIME_SHUTDOWN_SETTLE_MARGIN_MS, executionCancelGraceMs + RUNTIME_SHUTDOWN_SETTLE_MARGIN_MS)
}

export const DESKTOP_SERVER_SHUTDOWN_TIMEOUT_MS =
  resolveRuntimeShutdownTimeoutMs(MAX_EXECUTION_CANCEL_GRACE_MS) + DESKTOP_SUPERVISOR_SETTLE_MARGIN_MS
