export const directoryCopy = {
  selectCurrent: { id: "directory.navigation.selectCurrent", message: "Select this folder" },
  title: { id: "directory.navigation.title", message: "Choose a folder" },
  service: { id: "directory.navigation.service", message: "Browsing folders on {service}" },
  path: { id: "directory.navigation.path", message: "Folder path" },
  editPath: { id: "directory.navigation.editPath", message: "Edit path" },
  current: { id: "directory.navigation.current", message: "Current folder" },
  home: { id: "directory.navigation.home", message: "Home folder" },
  up: { id: "directory.navigation.up", message: "Parent folder" },
  go: { id: "directory.navigation.go", message: "Go" },
  search: { id: "directory.navigation.search", message: "Search folders here" },
  enter: { id: "directory.navigation.enter", message: "Open folder" },
  hidden: { id: "directory.navigation.hidden", message: "Show hidden folders" },
  loading: { id: "directory.navigation.loading", message: "Loading folders…" },
  empty: { id: "directory.navigation.empty", message: "This folder has no subfolders. You can use this folder." },
  noResults: { id: "directory.navigation.noResults", message: "No matching folders. Try another search." },
  denied: {
    id: "directory.navigation.denied",
    message: "This service cannot read this folder. Check its access permissions or choose another path.",
  },
  missing: { id: "directory.navigation.missing", message: "This folder does not exist on the connected service." },
  notFolder: { id: "directory.navigation.notFolder", message: "This path is a file. Enter a folder path." },
  failed: {
    id: "directory.navigation.failed",
    message: "Could not load folders. Check the service connection and retry.",
  },
  retry: { id: "directory.navigation.retry", message: "Retry" },
  more: { id: "directory.navigation.more", message: "Load more folders" },
  selected: { id: "directory.navigation.selected", message: "{count} folders selected" },
  clear: { id: "directory.navigation.clear", message: "Clear selection" },
  use: { id: "directory.navigation.use", message: "Use this folder" },
  useMany: { id: "directory.navigation.useMany", message: "Use selected folders" },
  cancel: { id: "directory.navigation.cancel", message: "Cancel" },
  searchLimit: {
    id: "directory.navigation.searchLimit",
    message: "Showing the first 200 matches. Narrow your search to find more.",
  },
} as const
