export const projectEntryCopy = {
  changed: {
    id: "project.entry.changed",
    message: "Project folders changed. Review the selected main folder, then start the task again.",
  },
  computer: { id: "project.entry.computer", message: "Computer" },
  manageComputers: { id: "project.entry.manageComputers", message: "Manage computers" },
  connected: { id: "project.entry.connected", message: "Connected" },
  unavailable: { id: "project.entry.unavailable", message: "Unavailable" },
  create: { id: "project.entry.create", message: "New project" },
  createAction: { id: "project.entry.createAction", message: "Create project" },
  creating: { id: "project.entry.creating", message: "Creating…" },
  created: { id: "project.entry.created", message: "Project created" },
  name: { id: "project.entry.name", message: "Project name" },
  namePlaceholder: { id: "project.entry.namePlaceholder", message: "Name your project" },
  folders: { id: "project.entry.folders", message: "Folders" },
  chooseFolders: { id: "project.entry.chooseFolders", message: "Choose folders" },
  addFolder: { id: "project.entry.addFolder", message: "Add folder" },
  main: { id: "project.entry.main", message: "Main folder" },
  originalMain: { id: "project.entry.originalMain", message: "Previous main folder" },
  setMain: { id: "project.entry.setMain", message: "Set as main folder" },
  remove: { id: "project.entry.remove", message: "Remove" },
  mainRemove: { id: "project.entry.mainRemove", message: "Choose another main folder before removing this one." },
  folderActions: { id: "project.entry.folderActions", message: "Folder actions" },
  existing: { id: "project.entry.existing", message: "This folder already belongs to a project." },
  openExisting: { id: "project.entry.openExisting", message: "Open existing project" },
  failed: { id: "project.entry.failed", message: "Could not save project" },
  settings: { id: "project.entry.settings", message: "Project settings" },
  start: { id: "project.entry.start", message: "Start new tasks in" },
  newWorktree: { id: "project.entry.newWorktree", message: "New Worktree" },
  worktrees: { id: "project.entry.worktrees", message: "Worktrees" },
  manageWorktrees: { id: "project.entry.manageWorktrees", message: "Manage Worktrees" },
  shared: { id: "project.entry.shared", message: "Based on {folder}; {count} other folders stay shared." },
  onSend: { id: "project.entry.onSend", message: "Created when you start the task." },
  folderImpact: {
    id: "project.entry.folderImpact",
    message:
      "The main folder applies to new tasks. Other folders are shared with existing tasks; disk files will not be moved or deleted.",
  },
  using: { id: "project.entry.using", message: "{count} linked tasks" },
  stale: { id: "project.entry.stale", message: "Folder unavailable" },
  emptyWorktrees: { id: "project.entry.emptyWorktrees", message: "No Worktrees yet" },
  deleteWorktree: { id: "project.entry.deleteWorktree", message: "Remove Worktree" },
  deleteDescription: {
    id: "project.entry.deleteDescription",
    message: "Remove this checkout from disk. Worktrees with changes are kept.",
  },
  use: { id: "project.entry.use", message: "Use Worktree" },
  retry: { id: "project.entry.retry", message: "Retry" },
  loading: { id: "project.entry.loading", message: "Loading…" },
  details: { id: "project.entry.details", message: "Details" },
  clean: { id: "project.entry.clean", message: "No uncommitted changes" },
  dirty: { id: "project.entry.dirty", message: "Uncommitted changes" },
  checked: { id: "project.entry.checked", message: "Checked {time}" },
  diskSize: { id: "project.entry.diskSize", message: "{size} MiB" },
  unsupported: {
    id: "project.entry.unsupported",
    message: "This task uses a custom location. Manage it in developer settings.",
  },
  developer: { id: "project.entry.developer", message: "Developer settings" },
} as const
