export const locationCopy = {
  running: {
    id: "task.location.running",
    message: "This task is running. You can change its working location when it finishes.",
  },
  browse: { id: "task.location.browse", message: "Browse folder" },
  searchFiles: { id: "task.location.searchFiles", message: "Search folders and file collections" },
  useFiles: { id: "task.location.useFiles", message: "Use these files" },
  cannotBrowse: {
    id: "task.location.cannotBrowse",
    message: "Use a file collection for this execution location; its folders cannot be browsed here.",
  },
  copyOnStart: {
    id: "task.location.copyOnStart",
    message: "A separate copy of the project files will be created when you send this task.",
  },
  copyDescription: {
    id: "task.location.copyDescription",
    message: "Create a separate copy of the project files for this task. Other tasks keep using their current files.",
  },
  copyName: { id: "task.location.copyName", message: "Copy name (optional)" },
  copyNameHint: { id: "task.location.copyNameHint", message: "For example, fix login" },
  createCopy: { id: "task.location.createCopy", message: "Create and use copy" },
  associated: { id: "task.location.associated", message: "Tasks using these files" },
  noAssociated: { id: "task.location.noAssociated", message: "No tasks currently use these files." },
  associatedFailed: {
    id: "task.location.associatedFailed",
    message: "Could not check affected tasks. Reload before changing the shared folder.",
  },

  continueCopy: { id: "task.location.continueCopy", message: "Continue an existing copy" },
  current: { id: "task.location.current", message: "Keep current location" },
  retry: { id: "task.location.retry", message: "Reload locations" },
  inherit: { id: "task.location.inherit", message: "Follow global default" },
  saved: { id: "task.location.saved", message: "Saved" },
  readOnlyDefaults: {
    id: "task.location.readOnlyDefaults",
    message: "This project has no configuration folder and follows global defaults.",
  },
  title: { id: "task.location.title", message: "Working location" },
  description: { id: "task.location.description", message: "Choose the files and execution location for this task." },
  files: { id: "task.location.files", message: "Main folder" },
  noFiles: { id: "task.location.noFiles", message: "No project files" },
  copy: { id: "task.location.copy", message: "Worktree" },
  planned: { id: "task.location.planned", message: "Worktree on start" },
  chooseFiles: { id: "task.location.chooseFiles", message: "Use another folder or file collection" },
  fileDescription: {
    id: "task.location.fileDescription",
    message: "Choose files for this task without changing another task’s folder.",
  },
  execution: { id: "task.location.execution", message: "Execution location" },
  executionDescription: {
    id: "task.location.executionDescription",
    message: "Commands run here when the task needs them. Choosing a location does not start compute.",
  },
  default: { id: "task.location.default", message: "Use project default" },
  none: { id: "task.location.none", message: "No command execution" },
  native: { id: "task.location.native", message: "Connected service" },
  mac: { id: "task.location.mac", message: "This Mac" },
  computer: { id: "task.location.computer", message: "This computer" },
  unavailable: { id: "task.location.unavailable", message: "Location unavailable" },
  incompatible: {
    id: "task.location.incompatible",
    message: "This location needs a compatible file collection; it cannot use this project folder.",
  },
  manage: { id: "task.location.manage", message: "Project settings" },
  advanced: { id: "task.location.advanced", message: "Technical details and resource management" },
  manageFiles: { id: "task.location.manageFiles", message: "Manage files and copies" },
  manageExecution: { id: "task.location.manageExecution", message: "Manage execution resources" },
  save: { id: "task.location.save", message: "Save" },
  cancel: { id: "task.location.cancel", message: "Cancel" },
  apply: { id: "task.location.apply", message: "Use this location" },
  failed: { id: "task.location.failed", message: "Could not change working location" },
  loading: { id: "task.location.loading", message: "Loading locations…" },
  defaults: { id: "task.location.defaults", message: "New task defaults" },
  defaultsDescription: {
    id: "task.location.defaultsDescription",
    message: "Applies to new tasks started here. Existing tasks keep their files and execution location.",
  },
  basic: { id: "task.location.basic", message: "Basic information" },
  discard: { id: "task.location.discard", message: "Discard changes" },
  discardDescription: { id: "task.location.discardDescription", message: "Your unsaved project changes will be lost." },
} as const
