export const PLUGIN_PROTOCOL_MIN_SYNERGY_VERSION = "2.4.3"
export const PLUGIN_PROTOCOL_MIN_SYNERGY_RANGE = `>=${PLUGIN_PROTOCOL_MIN_SYNERGY_VERSION}`
export const PLUGIN_STRUCTURED_THEME_MIN_SYNERGY_VERSION = "2.4.4"
export const PLUGIN_STRUCTURED_THEME_MIN_SYNERGY_RANGE = `>=${PLUGIN_STRUCTURED_THEME_MIN_SYNERGY_VERSION}`
export const PLUGIN_UI_API_VERSION = "3.0"
export const PLUGIN_API_VERSION = "3.0" as const
export const PLUGIN_MANIFEST_VERSION = 1 as const
export const PLUGIN_RUNTIME_PROTOCOL_VERSION = 2 as const
