import { darken, lighten, withAlpha } from "./color"
import type { HexColor, Theme } from "./types"
import synergyThemeJson from "./themes/synergy.json"
import { parseTheme } from "./schema"

export const synergyTheme: Theme = parseTheme(synergyThemeJson)

type Palette = {
  background: HexColor
  canvas: HexColor
  surface: HexColor
  hover: HexColor
  inset: HexColor
  selection: HexColor
  text: HexColor
  textWeak: HexColor
  textSubtle: HexColor
  accent: HexColor
  link: HexColor
  success: HexColor
  warning: HexColor
  error: HexColor
  syntaxString: HexColor
  syntaxKeyword: HexColor
  syntaxType: HexColor
}

function themedOverrides(palette: Palette, dark: boolean) {
  const border = (opacity: number) => withAlpha(palette.text, opacity)
  const active = dark ? lighten(palette.hover, 0.06) : darken(palette.hover, 0.05)

  return {
    "background-base": palette.background,
    "background-weak": palette.canvas,
    "background-strong": palette.background,
    "background-stronger": palette.canvas,
    "surface-base": palette.surface,
    base: palette.surface,
    base2: palette.surface,
    base3: palette.surface,
    "surface-hover-base": palette.surface,
    "surface-base-hover": palette.hover,
    "surface-base-active": active,
    "surface-base-interactive-active": active,
    "surface-inset-base": palette.inset,
    "surface-inset-base-hover": palette.hover,
    "surface-inset-strong": palette.inset,
    "surface-inset-strong-hover": palette.hover,
    "surface-raised-base": palette.surface,
    "surface-raised-base-hover": palette.hover,
    "surface-raised-base-active": active,
    "surface-raised-strong": palette.surface,
    "surface-raised-strong-hover": palette.hover,
    "surface-raised-stronger": palette.hover,
    "surface-raised-stronger-hover": active,
    "surface-raised-stronger-non-alpha": palette.hover,
    "surface-weak": palette.canvas,
    "surface-weaker": palette.inset,
    "surface-strong": palette.hover,
    "surface-hover": palette.hover,
    "surface-disabled": palette.inset,
    "surface-float-base": palette.surface,
    "surface-float-base-hover": palette.hover,
    "surface-focus": withAlpha(palette.link, 0.16),
    "surface-interactive-selected": palette.selection,
    "surface-interactive-selected-weak": palette.inset,
    "input-base": palette.inset,
    "input-hover": palette.hover,
    "input-active": active,
    "input-selected": palette.selection,
    "input-focus": palette.hover,
    "input-disabled": palette.inset,
    "button-secondary-base": palette.inset,
    "button-secondary-hover": palette.hover,
    "text-base": palette.text,
    "text-weak": palette.textWeak,
    "text-weaker": palette.textWeak,
    "text-subtle": palette.textSubtle,
    "text-strong": palette.text,
    "text-interactive-base": palette.link,
    "icon-base": palette.text,
    "icon-hover": palette.text,
    "icon-weak-base": palette.textWeak,
    "icon-weak-hover": palette.text,
    "border-color": palette.background,
    "border-base": border(dark ? 0.22 : 0.16),
    "border-hover": border(dark ? 0.28 : 0.22),
    "border-active": border(dark ? 0.34 : 0.28),
    "border-disabled": border(dark ? 0.16 : 0.11),
    "border-focus": palette.link,
    "border-weak-base": border(dark ? 0.16 : 0.11),
    "border-weak-hover": border(dark ? 0.22 : 0.16),
    "border-weak-active": border(dark ? 0.28 : 0.22),
    "border-weak-disabled": border(dark ? 0.16 : 0.11),
    "border-weak-focus": palette.link,
    "border-weaker-base": border(dark ? 0.1 : 0.07),
    "border-weaker-hover": border(dark ? 0.16 : 0.11),
    "border-weaker-active": border(dark ? 0.22 : 0.16),
    "border-weaker-disabled": border(dark ? 0.1 : 0.07),
    "border-weaker-focus": palette.link,
    "border-strong-base": border(dark ? 0.3 : 0.23),
    "border-strong-hover": border(dark ? 0.36 : 0.29),
    "border-strong-active": border(dark ? 0.42 : 0.35),
    "border-strong-disabled": border(dark ? 0.22 : 0.16),
    "border-strong-focus": palette.link,
    "border-selected": withAlpha(palette.accent, dark ? 0.7 : 0.58),
    "border-strong-selected": withAlpha(palette.accent, dark ? 0.56 : 0.46),
    "border-weak-selected": withAlpha(palette.accent, dark ? 0.38 : 0.3),
    "border-weaker-selected": withAlpha(palette.accent, dark ? 0.22 : 0.18),
    "border-interactive-base": palette.accent,
    "border-interactive-selected": withAlpha(palette.accent, dark ? 0.7 : 0.58),
    "markdown-heading": palette.text,
    "markdown-text": palette.text,
    "markdown-link": palette.link,
    "markdown-link-text": palette.link,
    "markdown-code": palette.textWeak,
    "markdown-block-quote": palette.textWeak,
    "markdown-emph": palette.textWeak,
    "markdown-strong": palette.text,
    "markdown-horizontal-rule": border(dark ? 0.28 : 0.2),
    "markdown-list-item": palette.textWeak,
    "markdown-list-enumeration": palette.textWeak,
    "markdown-image": palette.link,
    "markdown-image-text": palette.link,
    "markdown-code-block": palette.text,
    "syntax-comment": "var(--text-weaker)",
    "syntax-regexp": palette.text,
    "syntax-string": palette.syntaxString,
    "syntax-keyword": palette.syntaxKeyword,
    "syntax-primitive": palette.accent,
    "syntax-operator": palette.textWeak,
    "syntax-variable": palette.text,
    "syntax-property": palette.link,
    "syntax-type": palette.syntaxType,
    "syntax-constant": palette.accent,
    "syntax-punctuation": palette.textWeak,
    "syntax-object": palette.text,
    "syntax-info": palette.link,
    "syntax-diff-unknown": palette.error,
  } as const
}

function createTheme(id: string, name: string, light: Palette, dark: Palette): Theme {
  return parseTheme({
    ...synergyTheme,
    id,
    name,
    light: {
      ...synergyTheme.light,
      seeds: {
        ...synergyTheme.light.seeds,
        neutral: light.textWeak,
        primary: light.accent,
        success: light.success,
        warning: light.warning,
        error: light.error,
        info: light.accent,
        interactive: light.accent,
        diffAdd: light.success,
        diffDelete: light.error,
      },
      overrides: themedOverrides(light, false),
    },
    dark: {
      ...synergyTheme.dark,
      seeds: {
        ...synergyTheme.dark.seeds,
        neutral: dark.textWeak,
        primary: dark.accent,
        success: dark.success,
        warning: dark.warning,
        error: dark.error,
        info: dark.accent,
        interactive: dark.accent,
        diffAdd: dark.success,
        diffDelete: dark.error,
      },
      overrides: themedOverrides(dark, true),
    },
  })
}

// Catppuccin Latte / Mocha palette, MIT: https://github.com/catppuccin/palette
export const catppuccinTheme = createTheme(
  "catppuccin",
  "Catppuccin",
  {
    background: "#EFF1F5",
    canvas: "#E6E9EF",
    surface: "#FFFFFF",
    hover: "#DCE0E8",
    inset: "#E6E9EF",
    selection: "#CCD0DA",
    text: "#4C4F69",
    textWeak: "#5C5F77",
    textSubtle: "#8C8FA1",
    accent: "#1E66F5",
    link: "#1A5CCF",
    success: "#40A02B",
    warning: "#DF8E1D",
    error: "#D20F39",
    syntaxString: "#40A02B",
    syntaxKeyword: "#8839EF",
    syntaxType: "#179299",
  },
  {
    background: "#1E1E2E",
    canvas: "#181825",
    surface: "#1E1E2E",
    hover: "#313244",
    inset: "#181825",
    selection: "#45475A",
    text: "#CDD6F4",
    textWeak: "#BAC2DE",
    textSubtle: "#A6ADC8",
    accent: "#89B4FA",
    link: "#89B4FA",
    success: "#A6E3A1",
    warning: "#F9E2AF",
    error: "#F38BA8",
    syntaxString: "#A6E3A1",
    syntaxKeyword: "#CBA6F7",
    syntaxType: "#94E2D5",
  },
)

// Tokyo Night Day / Moon palette, Apache-2.0: https://github.com/folke/tokyonight.nvim
export const tokyoNightTheme = createTheme(
  "tokyo-night",
  "Tokyo Night",
  {
    background: "#E1E2E7",
    canvas: "#D5D6DB",
    surface: "#E9E9ED",
    hover: "#D0D5E3",
    inset: "#D5D6DB",
    selection: "#C4C8DA",
    text: "#34548A",
    textWeak: "#4C5F97",
    textSubtle: "#8990B3",
    accent: "#2E7DE9",
    link: "#34548A",
    success: "#587539",
    warning: "#B15C00",
    error: "#F52A65",
    syntaxString: "#587539",
    syntaxKeyword: "#7847BD",
    syntaxType: "#007197",
  },
  {
    background: "#222436",
    canvas: "#1E2030",
    surface: "#222436",
    hover: "#2F334D",
    inset: "#1E2030",
    selection: "#3B4261",
    text: "#C8D3F5",
    textWeak: "#A9B1D6",
    textSubtle: "#828BB8",
    accent: "#82AAFF",
    link: "#82AAFF",
    success: "#C3E88D",
    warning: "#FFC777",
    error: "#FF757F",
    syntaxString: "#C3E88D",
    syntaxKeyword: "#C099FF",
    syntaxType: "#86E1FC",
  },
)

// Ayu Light / Mirage palette, MIT: https://github.com/ayu-theme/ayu-colors
export const ayuTheme = createTheme(
  "ayu",
  "Ayu",
  {
    background: "#FAFAFA",
    canvas: "#F3F4F5",
    surface: "#FFFFFF",
    hover: "#EEF0F2",
    inset: "#F3F4F5",
    selection: "#E7EAEB",
    text: "#575F66",
    textWeak: "#6C7680",
    textSubtle: "#8A9199",
    accent: "#FF9940",
    link: "#005CC5",
    success: "#6A9F00",
    warning: "#C58B00",
    error: "#E65050",
    syntaxString: "#6A9F00",
    syntaxKeyword: "#A37ACC",
    syntaxType: "#399EE6",
  },
  {
    background: "#1F2430",
    canvas: "#191E2A",
    surface: "#242936",
    hover: "#303747",
    inset: "#1B202B",
    selection: "#33415E",
    text: "#CCCAC2",
    textWeak: "#B8C0CC",
    textSubtle: "#7A8699",
    accent: "#FFCC66",
    link: "#73D0FF",
    success: "#BAE67E",
    warning: "#FFCC66",
    error: "#F07178",
    syntaxString: "#BAE67E",
    syntaxKeyword: "#D2A6FF",
    syntaxType: "#73D0FF",
  },
)

// Rose Pine Dawn / Moon palette, MIT: https://github.com/rose-pine/rose-pine-theme
export const rosePineTheme = createTheme(
  "rose-pine",
  "Rose Pine",
  {
    background: "#FAF4ED",
    canvas: "#F2E9DE",
    surface: "#FFFAF3",
    hover: "#F2E9DE",
    inset: "#F2E9DE",
    selection: "#DFD6CA",
    text: "#575279",
    textWeak: "#6E6A86",
    textSubtle: "#9893A5",
    accent: "#907AA9",
    link: "#286983",
    success: "#56949F",
    warning: "#EA9D34",
    error: "#B4637A",
    syntaxString: "#56949F",
    syntaxKeyword: "#907AA9",
    syntaxType: "#286983",
  },
  {
    background: "#232136",
    canvas: "#191724",
    surface: "#2A273F",
    hover: "#393552",
    inset: "#191724",
    selection: "#44415A",
    text: "#E0DEF4",
    textWeak: "#C4C1D8",
    textSubtle: "#908CAA",
    accent: "#C4A7E7",
    link: "#9CCFD8",
    success: "#9CCFD8",
    warning: "#F6C177",
    error: "#EB6F92",
    syntaxString: "#9CCFD8",
    syntaxKeyword: "#C4A7E7",
    syntaxType: "#3E8FB0",
  },
)

// Kanagawa Lotus / Wave palette, MIT: https://github.com/rebelot/kanagawa.nvim
export const kanagawaTheme = createTheme(
  "kanagawa",
  "Kanagawa",
  {
    background: "#F2ECBC",
    canvas: "#E5DDB0",
    surface: "#F7F2D0",
    hover: "#E4D794",
    inset: "#E5DDB0",
    selection: "#DCD5A0",
    text: "#545464",
    textWeak: "#6A6A84",
    textSubtle: "#8A8980",
    accent: "#4D699B",
    link: "#4D699B",
    success: "#6F894E",
    warning: "#77713F",
    error: "#C84053",
    syntaxString: "#6F894E",
    syntaxKeyword: "#624C83",
    syntaxType: "#597B75",
  },
  {
    background: "#1F1F28",
    canvas: "#16161D",
    surface: "#2A2A37",
    hover: "#363646",
    inset: "#16161D",
    selection: "#2D4F67",
    text: "#DCD7BA",
    textWeak: "#C8C093",
    textSubtle: "#727169",
    accent: "#7E9CD8",
    link: "#7FB4CA",
    success: "#98BB6C",
    warning: "#E6C384",
    error: "#E46876",
    syntaxString: "#98BB6C",
    syntaxKeyword: "#957FB8",
    syntaxType: "#7AA89F",
  },
)

// Everforest Light / Dark palette, MIT: https://github.com/sainnhe/everforest
export const everforestTheme = createTheme(
  "everforest",
  "Everforest",
  {
    background: "#FDF6E3",
    canvas: "#F3EAD3",
    surface: "#F4F0D9",
    hover: "#EDE5CE",
    inset: "#F3EAD3",
    selection: "#E1D8C1",
    text: "#58656C",
    textWeak: "#58656C",
    textSubtle: "#859289",
    accent: "#3A94C5",
    link: "#2377A4",
    success: "#8DA101",
    warning: "#DFA000",
    error: "#F85552",
    syntaxString: "#8DA101",
    syntaxKeyword: "#DF69BA",
    syntaxType: "#35A77C",
  },
  {
    background: "#2D353B",
    canvas: "#232A2E",
    surface: "#343F44",
    hover: "#3D484D",
    inset: "#293136",
    selection: "#4A555B",
    text: "#D3C6AA",
    textWeak: "#B9B89A",
    textSubtle: "#859289",
    accent: "#7FBBB3",
    link: "#83C092",
    success: "#A7C080",
    warning: "#DBBC7F",
    error: "#E67E80",
    syntaxString: "#A7C080",
    syntaxKeyword: "#D699B6",
    syntaxType: "#83C092",
  },
)

// Solarized Light / Dark palette, MIT: https://github.com/altercation/solarized
export const solarizedTheme = createTheme(
  "solarized",
  "Solarized",
  {
    background: "#FDF6E3",
    canvas: "#EEE8D5",
    surface: "#FDF6E3",
    hover: "#E4DDC7",
    inset: "#EEE8D5",
    selection: "#D5CFB9",
    text: "#4F6369",
    textWeak: "#4F6369",
    textSubtle: "#839496",
    accent: "#268BD2",
    link: "#00758F",
    success: "#859900",
    warning: "#B58900",
    error: "#DC322F",
    syntaxString: "#859900",
    syntaxKeyword: "#6C71C4",
    syntaxType: "#2AA198",
  },
  {
    background: "#002B36",
    canvas: "#073642",
    surface: "#073642",
    hover: "#073642",
    inset: "#002B36",
    selection: "#094B5C",
    text: "#93A1A1",
    textWeak: "#93A1A1",
    textSubtle: "#657B83",
    accent: "#2AA198",
    link: "#2AA198",
    success: "#859900",
    warning: "#B58900",
    error: "#DC322F",
    syntaxString: "#859900",
    syntaxKeyword: "#6C71C4",
    syntaxType: "#268BD2",
  },
)

export const builtinThemes = [
  synergyTheme,
  catppuccinTheme,
  tokyoNightTheme,
  ayuTheme,
  rosePineTheme,
  kanagawaTheme,
  everforestTheme,
  solarizedTheme,
] as const

export function getBuiltinTheme(id: string): Theme | undefined {
  return builtinThemes.find((theme) => theme.id === id)
}
