export {
  CSS_VAR_REF_PATTERN,
  HEX_COLOR_PATTERN,
  HEX_COLOR_REGEX,
  OPAQUE_HEX_COLOR_PATTERN,
  THEME_ALL_SEED_NAMES,
  THEME_CORE_SEED_NAMES,
  THEME_ID_PATTERN,
  THEME_SEED_NAMES,
  THEME_SYNTAX_SEED_NAMES,
  type ThemeAllSeedName,
  type ThemeCoreSeedName,
  type ThemeSeedName,
  type ThemeSeedInput,
  type ThemeSyntaxSeedName,
} from "@ericsanchezok/synergy-plugin/theme"
