#!/usr/bin/env bun

import path from "node:path"
import { runBatchedTests } from "../../../script/shared/test-runner"

const root = path.resolve(import.meta.dir, "..")
// Playwright suites launch Chromium. bun test runs files in parallel worker
// processes and reaps dangling children when a worker exits, which can kill a
// sibling suite's freshly launched browser. Run every Chromium suite serially
// after the main batch to keep their processes alive.
// These `mock.module`-heavy suites stub the same context modules under the same
// specifiers; Bun's mocks are process-global, so each needs its own process.
const playwrightIsolated = [
  "test/components/workspace/review-export.browser.test.ts",
  "test/components/execution/controls.render.test.ts",
  "test/components/execution/reader.dom.test.tsx",
  "test/components/execution/delegation.dom.test.tsx",
  "test/components/execution/layout.test.ts",
  "test/components/session/welcome/stage.dom.test.tsx",
  "test/components/session/workbench-navigation.render.test.ts",
  "test/components/session/workbench-layout.dom.test.tsx",
  "test/components/session/work-context.dom.test.ts",

  "test/components/workspace/builtin-workbench-panels.test.ts",
  "test/components/workspace/workspace-output-effects.test.ts",
  "test/components/note/documents.test.ts",

  "test/components/workspace/execution-detail.dom.test.ts",
  "test/components/workspace/browser/browser-draft.test.ts",
  "test/components/workspace/browser/browser-ws-reconnect.test.ts",
  "test/components/sidebar/sidebar-collections.dom.test.tsx",
  "test/components/agenda/agenda-interaction.dom.test.tsx",
  "test/components/app-shell/mobile-tools-drawer.dom.test.tsx",
  "test/components/library/library-interaction.dom.test.tsx",
  "test/components/workspace/browser/browser-interaction.dom.test.tsx",
  "test/components/workspace/browser/browser-panel-presentation.dom.test.tsx",
  "test/components/workspace/browser/browser-workbench-sync.dom.test.tsx",
  "test/components/session/session-recovery.dom.test.ts",
  "test/components/search/session-search-dialog.dom.test.ts",
  "test/components/toolbar-selector.dom.test.ts",
  "test/components/workspace/workbench-surface.dom.test.ts",
  "test/components/workspace/resource-home.dom.test.ts",
  "test/components/workspace/mobile-workspace-dialog.dom.test.ts",
  "test/components/performance/snapshot-boundary.dom.test.ts",
  "test/components/stats/presentation.dom.test.ts",
  "test/plugin/global-themes-registrar-lifecycle.test.tsx",
  "test/components/session/rollback-files.dom.test.ts",
  "test/components/session/session-review-workspace.dom.test.ts",
  "test/components/workspace/review-data.dom.test.ts",
  "test/components/session/conversation-reading-anchor.dom.test.ts",
  "test/components/session/conversation-process.dom.test.ts",
  "test/components/dialog/workspace-dialog.dom.test.ts",
  "test/components/dialog/directory-navigation.dom.test.ts",
  "test/components/dialog/directory-selection.dom.test.ts",
  "test/components/dialog/environment-dialog.dom.test.ts",
  "test/components/dialog/file-entry-dialog.dom.test.ts",
  "test/context/file/workspace.dom.test.ts",
  "test/components/kanban/layout.dom.test.tsx",
  "test/plugin/marketplace/marketplace.dom.test.tsx",
  "test/components/kanban/full-access-ack.test.ts",
  "test/components/prompt-input/full-access-ack.test.ts",
  "test/components/settings/panels/full-access-ack.test.ts",
  "test/components/settings/panels/StoragePanel.test.ts",
  "test/components/settings/panels/McpPanel.render.test.ts",
  "test/plugin/components.dom.test.ts",
  "test/plugin/overlays.dom.test.ts",
  "test/plugin/skin.dom.test.ts",
  "test/plugin/builtin-navigation.test.ts",
  "test/plugin/theme-config-bridge.test.ts",
  "test/components/prompt-input/editor.dom.test.ts",
  "test/components/app-shell/mobile-drawer-drag-region.test.tsx",
  "test/components/app-shell/mobile-drawer-root.test.tsx",
  "test/components/app-shell/model-unavailable-banner.test.tsx",
  "test/components/dialog/model-selector-layout.test.ts",
  "test/components/file-workbench/scrollbar-dark.test.ts",
  "test/components/file-workbench/selection.test.ts",
  "test/components/file-workbench/open-in-browser.dom.test.ts",
  "test/components/file-workbench/html-preview.dom.test.ts",
  "test/components/file-workbench/explorer-restore.dom.test.ts",
  "test/components/attachment-workbench/pdf-preview.dom.test.ts",
  "test/components/attachment-workbench/docx-reader.dom.test.ts",
  "test/components/attachment-workbench/xlsx-reader.dom.test.ts",
  "test/components/attachment-workbench/pptx-reader.dom.test.ts",
  "test/components/attachment-workbench/office-preview.dom.test.ts",
  "test/components/attachment-workbench/content.dom.test.ts",
  "test/components/attachment-workbench/office-integration.dom.test.ts",
  "test/components/prompt-input/composer-resize.dom.test.ts",
  "test/components/prompt-input/composer-motion.dom.test.ts",
  "test/components/prompt-input/attachments-layout.dom.test.ts",
  "test/components/library/filter-menu-surface.test.ts",
  "test/components/menu-field/menu-field.test.ts",
  "test/components/prompt-input/prompt-input-hover-style.test.ts",
  "test/components/prompt-input/pending-attachment-card.dom.test.tsx",
  "test/components/provider/model-thinking-picker.dom.test.tsx",
  "test/components/prompt-input/stop-control.render.test.ts",
  "test/components/settings/components/ThemePicker.behavior.test.tsx",
  "test/components/settings/settings-dialog-dismiss.test.tsx",
  "test/components/settings/storage-maintenance.test.ts",
  "test/components/settings/settings-mobile-layout.test.ts",
  "test/components/settings/panels/BossModePanel.test.ts",
  "test/components/settings/panels/VoicePanel.test.ts",
  "test/components/settings/settings-resource-flows.dom.test.tsx",
  "test/components/settings/settings-details.dom.test.tsx",
  "test/components/session/session-preparation.dom.test.tsx",
  "test/components/session/session-tag-menu.dom.test.tsx",
  "test/components/session/raw-messages-layout.test.ts",
  "test/components/settings/panels/interface-zoom.dom.test.ts",
  "test/components/session/conversation-row-retention.test.ts",
  "test/components/session/dialog-fork-confirm.dom.test.tsx",
  "test/components/session/decision-surface.dom.test.tsx",
  "test/components/session/prompt-dock-height.dom.test.tsx",
  "test/components/scopes/session-row.dom.test.tsx",
  "test/components/sidebar/session-draft-badge.dom.test.tsx",
  "test/components/sidebar/sidebar-attention-notice.dom.test.tsx",
  "test/components/sidebar/channel-sidebar-layout.test.ts",
  "test/components/workspace/browser/browser-recovery-state.test.tsx",
  "test/pages/fatal-error.dom.test.tsx",
]

await runBatchedTests({
  root,
  timeoutMs: 30000,
  isolated: playwrightIsolated,
  isolatedTimeoutMs: 120000,
  browserOnly: [
    "test/components/execution/controls.render.test.ts",
    "test/components/execution/trajectory.test.ts",
    "test/components/session/workbench-navigation.render.test.ts",
    "test/components/session/request-submission.test.ts",
    "test/components/search/session-search.test.ts",
    "test/components/performance/use-performance.test.ts",
    "test/components/library/use-library-stats.test.ts",
    "test/components/library/experience-details.test.ts",
    "test/components/library/library-collection.test.ts",
    "test/components/kanban/full-access-ack.test.ts",
    "test/components/prompt-input/full-access-ack.test.ts",
    "test/components/prompt-input/stop-control.render.test.ts",
    "test/components/settings/panels/StoragePanel.test.ts",
    "test/components/settings/panels/McpPanel.render.test.ts",
    "test/components/settings/panels/full-access-ack.test.ts",
    "test/plugin/shell-surface.test.ts",
    "test/plugin/shell-preference.test.ts",
    "test/components/note/document-editor-core.test.ts",
    "test/components/terminal/dispose-reentrancy.test.ts",
    "test/components/workspace/builtin-workbench-panels.test.ts",
    "test/components/workspace/workspace-output-effects.test.ts",
    "test/components/note/documents.test.ts",
    "test/context/font-preference-provider.test.ts",
    "test/context/layout/completion-notice.test.ts",
    "test/pages/fatal-error.test.tsx",
    "test/plugin/builtin-navigation.test.ts",
    "test/plugin/global-themes-registrar-lifecycle.test.tsx",
    "test/plugin/theme-config-bridge.test.ts",
    "test/plugin/registries/slot-outlet.test.ts",
    "test/plugin/registries/tool-renderer-registry.test.ts",
  ],
  extraSerial: ["test/app-build-css-contract.test.ts"],
})
