import type { MessageDescriptor } from "@lingui/core"

export const settingsFieldCopy = {
  learningLearn: { id: "settings.library.learning.learnRow.title", message: "Allow learning" },
  learningAutonomy: { id: "settings.library.learning.autonomyRow.title", message: "Autonomous routines" },
  memoryMatch: { id: "settings.library.memory.matchRow.title", message: "Match strictness" },
  memoryCount: { id: "settings.library.memory.countRow.title", message: "Memories per category" },
  memoryThreshold: { id: "settings.library.memory.preciseThreshold", message: "Memory similarity threshold" },
  experienceMatch: { id: "settings.library.experience.matchRow.title", message: "Match strictness" },
  experienceCount: { id: "settings.library.experience.countRow.title", message: "Experiences to recall" },
  experienceExploration: { id: "settings.library.experience.epsilonRow.title", message: "Exploration rate" },
  experienceThreshold: {
    id: "settings.library.experience.preciseThreshold",
    message: "Experience similarity threshold",
  },
  experienceProbability: { id: "settings.library.experience.preciseExploration", message: "Exploration probability" },
  encodingHealth: { id: "settings.library.encoding.health.title", message: "Encoding Health" },
  embeddingModel: {
    id: "settings.library.embedding.currentModel.title",
    message: "Current model",
  },
  embeddingSource: {
    id: "settings.library.embedding.downloadSource.title",
    message: "Download source",
  },
  embeddingOrigin: {
    id: "settings.library.embedding.customSource.title",
    message: "Custom source origin",
  },
  embeddingCache: {
    id: "settings.library.embedding.cacheDir.title",
    message: "Model cache directory",
  },
  embeddingFiles: {
    id: "settings.library.embedding.localFiles.title",
    message: "Local model files",
  },
  questionResponse: { id: "settings.runtime.questions.responseRow.title", message: "Response Timeout" },
  compactionAuto: { id: "settings.runtime.compaction.autoCompact.title", message: "Auto Compact" },
  compactionOverflow: { id: "settings.runtime.compaction.overflow.title", message: "Overflow Threshold" },
  compactionImages: { id: "settings.runtime.compaction.maxImages.title", message: "Max History Images" },
  agentWorkers: { id: "settings.runtime.agents.agentWorkers.title", message: "Parallel model requests" },
  agentConcurrency: { id: "settings.runtime.agents.concurrency.title", message: "Parallel collaborator tasks" },
  coauthor: { id: "settings.runtime.agents.coauthor.title", message: "Co-author Reminder" },
  defaultAgent: { id: "settings.runtime.agents.defaultAgent.title", message: "Default Agent" },
  invokeTimeout: { id: "settings.runtime.agents.invoke.title", message: "Invoke Timeout" },
  providerTtfb: { id: "settings.runtime.agents.ttfb.title", message: "TTFB Timeout" },
  providerIdle: { id: "settings.runtime.agents.idle.title", message: "Idle Timeout" },
  providerWall: { id: "settings.runtime.agents.wall.title", message: "Wall Timeout" },
  toolTimeout: { id: "settings.runtime.agents.toolTimeout.title", message: "Default Tool Timeout" },
  toolOverrides: { id: "settings.runtime.agents.overrides.title", message: "Tool Overrides" },
  codeInclude: { id: "settings.codeChecks.include.title", message: "Include Diagnostics" },
  codeSeverity: { id: "settings.codeChecks.severity.title", message: "Diagnostic Severity" },
  codeScope: { id: "settings.codeChecks.scope.title", message: "Diagnostic Scope" },
  bossPersonality: { id: "settings.runtime.boss.personality", message: "Collaboration style" },
  bossName: { id: "settings.runtime.boss.name", message: "Assistant name" },
  skillsAgents: { id: "settings.skills.agents.title", message: "Agent Skills" },
  skillsClaude: { id: "settings.skills.claude.title", message: "Claude Code" },
  skillsCodex: { id: "settings.skills.codex.title", message: "Codex" },
  skillsOpenclaw: { id: "settings.skills.openclaw.title", message: "OpenClaw" },
  customInstructions: { id: "settings.personalize.section.title", message: "Global custom instructions" },
} satisfies Record<string, MessageDescriptor>
