export const PLACEHOLDERS = [
  { id: "prompt.example.fixATodoInTheCodebase", message: "Fix a TODO in the codebase" },
  { id: "prompt.example.whatIsTheTechStackOfThis", message: "What is the tech stack of this project?" },
  { id: "prompt.example.fixBrokenTests", message: "Fix broken tests" },
  { id: "prompt.example.explainHowAuthenticationWorks", message: "Explain how authentication works" },
  { id: "prompt.example.findAndFixSecurityVulnerabilities", message: "Find and fix security vulnerabilities" },
  { id: "prompt.example.addUnitTestsForTheUserService", message: "Add unit tests for the user service" },
  { id: "prompt.example.refactorThisFunctionToBeMoreReadable", message: "Refactor this function to be more readable" },
  { id: "prompt.example.whatDoesThisErrorMean", message: "What does this error mean?" },
  { id: "prompt.example.helpMeDebugThisIssue", message: "Help me debug this issue" },
  { id: "prompt.example.generateApiDocumentation", message: "Generate API documentation" },
  { id: "prompt.example.optimizeDatabaseQueries", message: "Optimize database queries" },
  { id: "prompt.example.addInputValidation", message: "Add input validation" },
  { id: "prompt.example.createANewComponentFor", message: "Create a new component for..." },
  { id: "prompt.example.howDoIDeployThisProject", message: "How do I deploy this project?" },
  { id: "prompt.example.reviewMyCodeForBestPractices", message: "Review my code for best practices" },
  { id: "prompt.example.addErrorHandlingToThisFunction", message: "Add error handling to this function" },
  { id: "prompt.example.explainThisRegexPattern", message: "Explain this regex pattern" },
  { id: "prompt.example.convertThisToTypescript", message: "Convert this to TypeScript" },
  { id: "prompt.example.addLoggingThroughoutTheCodebase", message: "Add logging throughout the codebase" },
  { id: "prompt.example.whatDependenciesAreOutdated", message: "What dependencies are outdated?" },
  { id: "prompt.example.helpMeWriteAMigrationScript", message: "Help me write a migration script" },
  { id: "prompt.example.implementCachingForThisEndpoint", message: "Implement caching for this endpoint" },
  { id: "prompt.example.addPaginationToThisList", message: "Add pagination to this list" },
  { id: "prompt.example.createACliCommandFor", message: "Create a CLI command for..." },
  { id: "prompt.example.howDoEnvironmentVariablesWorkHere", message: "How do environment variables work here?" },
]

export const PLACEHOLDERS_GLOBAL = [
  { id: "prompt.example.whatSOnYourMind", message: "What's on your mind?" },
  { id: "prompt.example.helpMeWriteAnEmail", message: "Help me write an email" },
  { id: "prompt.example.summarizeThisArticleForMe", message: "Summarize this article for me" },
  { id: "prompt.example.brainstormIdeasFor", message: "Brainstorm ideas for..." },
  { id: "prompt.example.explainQuantumComputingSimply", message: "Explain quantum computing simply" },
  { id: "prompt.example.planATripToTokyo", message: "Plan a trip to Tokyo" },
  { id: "prompt.example.helpMePrepareForAnInterview", message: "Help me prepare for an interview" },
  { id: "prompt.example.draftABlogPostAbout", message: "Draft a blog post about..." },
  { id: "prompt.example.compareProsAndConsOf", message: "Compare pros and cons of..." },
  { id: "prompt.example.translateThisToFrench", message: "Translate this to French" },
]
