export const COMPUTER_DESC = {
  target: { id: "tool.computer.target", message: "Window" },
  accessibility: { id: "tool.computer.accessibility", message: "Accessibility" },
  image: { id: "tool.computer.image", message: "Window image" },
  delivery: { id: "tool.computer.delivery", message: "Model image input" },
  actions: { id: "tool.computer.actions", message: "Actions supported at observation" },
  diagnostics: { id: "tool.computer.diagnostics", message: "Observation details" },
  unknown: { id: "tool.computer.unknown", message: "Quality was not recorded" },
  available: { id: "tool.computer.available", message: "Available" },
  partial: { id: "tool.computer.partial", message: "Partial results" },
  unavailable: { id: "tool.computer.unavailable", message: "Unavailable" },
  valid: { id: "tool.computer.valid", message: "Verified image" },
  invalid: { id: "tool.computer.invalid", message: "Image rejected" },
  unverified: { id: "tool.computer.unverified", message: "Image not verified" },
  saved: { id: "tool.computer.saved", message: "Saved; model input pending" },
  included: { id: "tool.computer.included", message: "Included in model input" },
  submitted: { id: "tool.computer.submitted", message: "Sent with model request" },
  omitted: { id: "tool.computer.omitted", message: "Omitted from model input" },
  missing: { id: "tool.computer.missing", message: "Image attachment unavailable" },
  click: { id: "tool.computer.click", message: "Element click" },
  point: { id: "tool.computer.point", message: "Image point" },
  type: { id: "tool.computer.type", message: "Type text" },
  key: { id: "tool.computer.key", message: "Press key" },
  scroll: { id: "tool.computer.scroll", message: "Scroll" },
} as const
